stages:
  - build
  - deploy-develop

.restore-build:
  environment:
    NEXT_PUBLIC_API_BASE_URL: "https://ql-dev.dotlic.ru/"
  before_script:
    - git submodule sync && git submodule update --init --recursive
    - yarn install --frozen-lockfile
    - yarn workspace web-app run build
    - yarn workspace admin-app run build
    - yarn workspace user-dashboard run build

build:
  stage: build
  tags:
    - shell
    - ql-dev
  extends: .restore-build
  only:
    - merge_requests

deploy:
  stage: deploy-develop
  extends: .restore-build
  tags:
    - shell
    - ql-dev
  only:
    - develop
  script:
    # WEB (NEXT.JS Frontend)
    - sudo systemctl stop quartier-latin-web-dev
    - rm -rf /apps/quartier-dev/web && cp -r . /apps/quartier-dev/web/
    - sudo systemctl start quartier-latin-web-dev
    # Admin dashboard
    - sudo rm -rf /var/www/qladmin-dev/ && sudo cp -r packages/admin-app/build/ /var/www/qladmin-dev/
    - sudo chown -R www-data /var/www/qladmin-dev/
    # user-dashboard
    - sudo rm -rf /var/www/ql-user-dashboard-dev/ && sudo cp -r packages/user-dashboard/build/ /var/www/ql-user-dashboard-dev/
    - sudo chown -R www-data /var/www/ql-user-dashboard-dev/

