export enum UserStatus {
    INIT_PROFILE_STATUS,
    AUTHORIZED_PROFILE_STATUS,
    NOT_AUTHORIZED_PROFILE_STATUS,
}

export enum UserRegistrationStatus {
    REGISTRATION_COMPLITE_PROFILE_STATUS,
    NOT_REGISTRATION_COMPLITE_PROFILE_STATUS,
}